//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIF.GWSL.ExampleClient.CaseService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CaseParameterBase", Namespace="http://software-innovation.com/SI.Data")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SIF.GWSL.ExampleClient.CaseService.UpdateCaseParameter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SIF.GWSL.ExampleClient.CaseService.CreateCaseParameter))]
    public partial class CaseParameterBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ADContextUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccessCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccessGroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SIF.GWSL.ExampleClient.CaseService.AdditionalFieldParameter[] AdditionalFieldsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SIF.GWSL.ExampleClient.CaseService.ClassCodeParameter[] ArchiveCodesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SIF.GWSL.ExampleClient.CaseService.CaseContactParameter[] ContactsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SIF.GWSL.ExampleClient.CaseService.ExternalIdParameter ExternalIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> FiledOnPaperField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JournalUnitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] KeywordsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParagraphField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ReferringCasesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SIF.GWSL.ExampleClient.CaseService.Remark[] RemarksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponsibleEnterpriseNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ResponsibleEnterpriseRecnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponsiblePersonEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponsiblePersonIdNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ResponsiblePersonRecnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponsiblePersonUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ScrapCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> StartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubArchiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnofficialTitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ADContextUser {
            get {
                return this.ADContextUserField;
            }
            set {
                if ((object.ReferenceEquals(this.ADContextUserField, value) != true)) {
                    this.ADContextUserField = value;
                    this.RaisePropertyChanged("ADContextUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccessCode {
            get {
                return this.AccessCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.AccessCodeField, value) != true)) {
                    this.AccessCodeField = value;
                    this.RaisePropertyChanged("AccessCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccessGroup {
            get {
                return this.AccessGroupField;
            }
            set {
                if ((object.ReferenceEquals(this.AccessGroupField, value) != true)) {
                    this.AccessGroupField = value;
                    this.RaisePropertyChanged("AccessGroup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SIF.GWSL.ExampleClient.CaseService.AdditionalFieldParameter[] AdditionalFields {
            get {
                return this.AdditionalFieldsField;
            }
            set {
                if ((object.ReferenceEquals(this.AdditionalFieldsField, value) != true)) {
                    this.AdditionalFieldsField = value;
                    this.RaisePropertyChanged("AdditionalFields");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SIF.GWSL.ExampleClient.CaseService.ClassCodeParameter[] ArchiveCodes {
            get {
                return this.ArchiveCodesField;
            }
            set {
                if ((object.ReferenceEquals(this.ArchiveCodesField, value) != true)) {
                    this.ArchiveCodesField = value;
                    this.RaisePropertyChanged("ArchiveCodes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SIF.GWSL.ExampleClient.CaseService.CaseContactParameter[] Contacts {
            get {
                return this.ContactsField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactsField, value) != true)) {
                    this.ContactsField = value;
                    this.RaisePropertyChanged("Contacts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SIF.GWSL.ExampleClient.CaseService.ExternalIdParameter ExternalId {
            get {
                return this.ExternalIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalIdField, value) != true)) {
                    this.ExternalIdField = value;
                    this.RaisePropertyChanged("ExternalId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> FiledOnPaper {
            get {
                return this.FiledOnPaperField;
            }
            set {
                if ((this.FiledOnPaperField.Equals(value) != true)) {
                    this.FiledOnPaperField = value;
                    this.RaisePropertyChanged("FiledOnPaper");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JournalUnit {
            get {
                return this.JournalUnitField;
            }
            set {
                if ((object.ReferenceEquals(this.JournalUnitField, value) != true)) {
                    this.JournalUnitField = value;
                    this.RaisePropertyChanged("JournalUnit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Keywords {
            get {
                return this.KeywordsField;
            }
            set {
                if ((object.ReferenceEquals(this.KeywordsField, value) != true)) {
                    this.KeywordsField = value;
                    this.RaisePropertyChanged("Keywords");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Notes {
            get {
                return this.NotesField;
            }
            set {
                if ((object.ReferenceEquals(this.NotesField, value) != true)) {
                    this.NotesField = value;
                    this.RaisePropertyChanged("Notes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Paragraph {
            get {
                return this.ParagraphField;
            }
            set {
                if ((object.ReferenceEquals(this.ParagraphField, value) != true)) {
                    this.ParagraphField = value;
                    this.RaisePropertyChanged("Paragraph");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Project {
            get {
                return this.ProjectField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectField, value) != true)) {
                    this.ProjectField = value;
                    this.RaisePropertyChanged("Project");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ReferringCases {
            get {
                return this.ReferringCasesField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferringCasesField, value) != true)) {
                    this.ReferringCasesField = value;
                    this.RaisePropertyChanged("ReferringCases");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SIF.GWSL.ExampleClient.CaseService.Remark[] Remarks {
            get {
                return this.RemarksField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarksField, value) != true)) {
                    this.RemarksField = value;
                    this.RaisePropertyChanged("Remarks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponsibleEnterpriseNumber {
            get {
                return this.ResponsibleEnterpriseNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponsibleEnterpriseNumberField, value) != true)) {
                    this.ResponsibleEnterpriseNumberField = value;
                    this.RaisePropertyChanged("ResponsibleEnterpriseNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ResponsibleEnterpriseRecno {
            get {
                return this.ResponsibleEnterpriseRecnoField;
            }
            set {
                if ((this.ResponsibleEnterpriseRecnoField.Equals(value) != true)) {
                    this.ResponsibleEnterpriseRecnoField = value;
                    this.RaisePropertyChanged("ResponsibleEnterpriseRecno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponsiblePersonEmail {
            get {
                return this.ResponsiblePersonEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponsiblePersonEmailField, value) != true)) {
                    this.ResponsiblePersonEmailField = value;
                    this.RaisePropertyChanged("ResponsiblePersonEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponsiblePersonIdNumber {
            get {
                return this.ResponsiblePersonIdNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponsiblePersonIdNumberField, value) != true)) {
                    this.ResponsiblePersonIdNumberField = value;
                    this.RaisePropertyChanged("ResponsiblePersonIdNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ResponsiblePersonRecno {
            get {
                return this.ResponsiblePersonRecnoField;
            }
            set {
                if ((this.ResponsiblePersonRecnoField.Equals(value) != true)) {
                    this.ResponsiblePersonRecnoField = value;
                    this.RaisePropertyChanged("ResponsiblePersonRecno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponsiblePersonUserId {
            get {
                return this.ResponsiblePersonUserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponsiblePersonUserIdField, value) != true)) {
                    this.ResponsiblePersonUserIdField = value;
                    this.RaisePropertyChanged("ResponsiblePersonUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ScrapCode {
            get {
                return this.ScrapCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ScrapCodeField, value) != true)) {
                    this.ScrapCodeField = value;
                    this.RaisePropertyChanged("ScrapCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubArchive {
            get {
                return this.SubArchiveField;
            }
            set {
                if ((object.ReferenceEquals(this.SubArchiveField, value) != true)) {
                    this.SubArchiveField = value;
                    this.RaisePropertyChanged("SubArchive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnofficialTitle {
            get {
                return this.UnofficialTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.UnofficialTitleField, value) != true)) {
                    this.UnofficialTitleField = value;
                    this.RaisePropertyChanged("UnofficialTitle");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExternalIdParameter", Namespace="http://software-innovation.com/SI.Data")]
    [System.SerializableAttribute()]
    public partial class ExternalIdParameter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateCaseParameter", Namespace="http://software-innovation.com/SI.Data")]
    [System.SerializableAttribute()]
    public partial class UpdateCaseParameter : SIF.GWSL.ExampleClient.CaseService.CaseParameterBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CaseNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CaseNumber {
            get {
                return this.CaseNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CaseNumberField, value) != true)) {
                    this.CaseNumberField = value;
                    this.RaisePropertyChanged("CaseNumber");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateCaseParameter", Namespace="http://software-innovation.com/SI.Data")]
    [System.SerializableAttribute()]
    public partial class CreateCaseParameter : SIF.GWSL.ExampleClient.CaseService.CaseParameterBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CaseTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ClosedDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CaseType {
            get {
                return this.CaseTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.CaseTypeField, value) != true)) {
                    this.CaseTypeField = value;
                    this.RaisePropertyChanged("CaseType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ClosedDate {
            get {
                return this.ClosedDateField;
            }
            set {
                if ((this.ClosedDateField.Equals(value) != true)) {
                    this.ClosedDateField = value;
                    this.RaisePropertyChanged("ClosedDate");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdditionalFieldParameter", Namespace="http://software-innovation.com/SI.Data")]
    [System.SerializableAttribute()]
    public partial class AdditionalFieldParameter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClassCodeParameter", Namespace="http://software-innovation.com/SI.Data")]
    [System.SerializableAttribute()]
    public partial class ClassCodeParameter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArchiveCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArchiveTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsManualTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SortField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArchiveCode {
            get {
                return this.ArchiveCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ArchiveCodeField, value) != true)) {
                    this.ArchiveCodeField = value;
                    this.RaisePropertyChanged("ArchiveCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArchiveType {
            get {
                return this.ArchiveTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ArchiveTypeField, value) != true)) {
                    this.ArchiveTypeField = value;
                    this.RaisePropertyChanged("ArchiveType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsManualText {
            get {
                return this.IsManualTextField;
            }
            set {
                if ((this.IsManualTextField.Equals(value) != true)) {
                    this.IsManualTextField = value;
                    this.RaisePropertyChanged("IsManualText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sort {
            get {
                return this.SortField;
            }
            set {
                if ((this.SortField.Equals(value) != true)) {
                    this.SortField = value;
                    this.RaisePropertyChanged("Sort");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CaseContactParameter", Namespace="http://software-innovation.com/SI.Data")]
    [System.SerializableAttribute()]
    public partial class CaseContactParameter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsUnofficialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenceNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactId {
            get {
                return this.ContactIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactIdField, value) != true)) {
                    this.ContactIdField = value;
                    this.RaisePropertyChanged("ContactId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalId {
            get {
                return this.ExternalIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalIdField, value) != true)) {
                    this.ExternalIdField = value;
                    this.RaisePropertyChanged("ExternalId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsUnofficial {
            get {
                return this.IsUnofficialField;
            }
            set {
                if ((this.IsUnofficialField.Equals(value) != true)) {
                    this.IsUnofficialField = value;
                    this.RaisePropertyChanged("IsUnofficial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferenceNumber {
            get {
                return this.ReferenceNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceNumberField, value) != true)) {
                    this.ReferenceNumberField = value;
                    this.RaisePropertyChanged("ReferenceNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Role {
            get {
                return this.RoleField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleField, value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Remark", Namespace="http://software-innovation.com/SI.Data")]
    [System.SerializableAttribute()]
    public partial class Remark : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarkTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RemarkType {
            get {
                return this.RemarkTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarkTypeField, value) != true)) {
                    this.RemarkTypeField = value;
                    this.RaisePropertyChanged("RemarkType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WSOperationResult", Namespace="http://software-innovation.com/SI.Data")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SIF.GWSL.ExampleClient.CaseService.GetCasesResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SIF.GWSL.ExampleClient.CaseService.CaseOperationResult))]
    public partial class WSOperationResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessfulField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDetails {
            get {
                return this.ErrorDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorDetailsField, value) != true)) {
                    this.ErrorDetailsField = value;
                    this.RaisePropertyChanged("ErrorDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Successful {
            get {
                return this.SuccessfulField;
            }
            set {
                if ((this.SuccessfulField.Equals(value) != true)) {
                    this.SuccessfulField = value;
                    this.RaisePropertyChanged("Successful");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCasesResult", Namespace="http://software-innovation.com/SI.Data")]
    [System.SerializableAttribute()]
    public partial class GetCasesResult : SIF.GWSL.ExampleClient.CaseService.WSOperationResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SIF.GWSL.ExampleClient.CaseService.CaseResult[] CasesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SIF.GWSL.ExampleClient.CaseService.CaseResult[] Cases {
            get {
                return this.CasesField;
            }
            set {
                if ((object.ReferenceEquals(this.CasesField, value) != true)) {
                    this.CasesField = value;
                    this.RaisePropertyChanged("Cases");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CaseOperationResult", Namespace="http://schemas.datacontract.org/2004/07/SI.Data.Contracts.WS")]
    [System.SerializableAttribute()]
    public partial class CaseOperationResult : SIF.GWSL.ExampleClient.CaseService.WSOperationResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CaseNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RecnoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CaseNumber {
            get {
                return this.CaseNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CaseNumberField, value) != true)) {
                    this.CaseNumberField = value;
                    this.RaisePropertyChanged("CaseNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Recno {
            get {
                return this.RecnoField;
            }
            set {
                if ((this.RecnoField.Equals(value) != true)) {
                    this.RecnoField = value;
                    this.RaisePropertyChanged("Recno");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CaseResult", Namespace="http://software-innovation.com/SI.Data")]
    [System.SerializableAttribute()]
    public partial class CaseResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccessCodeCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccessCodeDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccessGroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SIF.GWSL.ExampleClient.CaseService.ArchiveCodeResult[] ArchiveCodesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CaseNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SIF.GWSL.ExampleClient.CaseService.CaseDocumentResult[] DocumentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SIF.GWSL.ExampleClient.CaseService.ExternalIdParameter ExternalIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParagraphField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RecnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SIF.GWSL.ExampleClient.CaseService.CaseCaseRelationResult[] ReferringCasesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SIF.GWSL.ExampleClient.CaseService.CaseDocumentRelationResult[] ReferringDocumentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SIF.GWSL.ExampleClient.CaseService.ResponsibleEnterprise ResponsibleEnterpriseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponsibleEnterpriseNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SIF.GWSL.ExampleClient.CaseService.ResponsiblePerson ResponsiblePersonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponsiblePersonNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccessCodeCode {
            get {
                return this.AccessCodeCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.AccessCodeCodeField, value) != true)) {
                    this.AccessCodeCodeField = value;
                    this.RaisePropertyChanged("AccessCodeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccessCodeDescription {
            get {
                return this.AccessCodeDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.AccessCodeDescriptionField, value) != true)) {
                    this.AccessCodeDescriptionField = value;
                    this.RaisePropertyChanged("AccessCodeDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccessGroup {
            get {
                return this.AccessGroupField;
            }
            set {
                if ((object.ReferenceEquals(this.AccessGroupField, value) != true)) {
                    this.AccessGroupField = value;
                    this.RaisePropertyChanged("AccessGroup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SIF.GWSL.ExampleClient.CaseService.ArchiveCodeResult[] ArchiveCodes {
            get {
                return this.ArchiveCodesField;
            }
            set {
                if ((object.ReferenceEquals(this.ArchiveCodesField, value) != true)) {
                    this.ArchiveCodesField = value;
                    this.RaisePropertyChanged("ArchiveCodes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CaseNumber {
            get {
                return this.CaseNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CaseNumberField, value) != true)) {
                    this.CaseNumberField = value;
                    this.RaisePropertyChanged("CaseNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SIF.GWSL.ExampleClient.CaseService.CaseDocumentResult[] Documents {
            get {
                return this.DocumentsField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentsField, value) != true)) {
                    this.DocumentsField = value;
                    this.RaisePropertyChanged("Documents");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SIF.GWSL.ExampleClient.CaseService.ExternalIdParameter ExternalId {
            get {
                return this.ExternalIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalIdField, value) != true)) {
                    this.ExternalIdField = value;
                    this.RaisePropertyChanged("ExternalId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Paragraph {
            get {
                return this.ParagraphField;
            }
            set {
                if ((object.ReferenceEquals(this.ParagraphField, value) != true)) {
                    this.ParagraphField = value;
                    this.RaisePropertyChanged("Paragraph");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Recno {
            get {
                return this.RecnoField;
            }
            set {
                if ((this.RecnoField.Equals(value) != true)) {
                    this.RecnoField = value;
                    this.RaisePropertyChanged("Recno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SIF.GWSL.ExampleClient.CaseService.CaseCaseRelationResult[] ReferringCases {
            get {
                return this.ReferringCasesField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferringCasesField, value) != true)) {
                    this.ReferringCasesField = value;
                    this.RaisePropertyChanged("ReferringCases");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SIF.GWSL.ExampleClient.CaseService.CaseDocumentRelationResult[] ReferringDocuments {
            get {
                return this.ReferringDocumentsField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferringDocumentsField, value) != true)) {
                    this.ReferringDocumentsField = value;
                    this.RaisePropertyChanged("ReferringDocuments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SIF.GWSL.ExampleClient.CaseService.ResponsibleEnterprise ResponsibleEnterprise {
            get {
                return this.ResponsibleEnterpriseField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponsibleEnterpriseField, value) != true)) {
                    this.ResponsibleEnterpriseField = value;
                    this.RaisePropertyChanged("ResponsibleEnterprise");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponsibleEnterpriseName {
            get {
                return this.ResponsibleEnterpriseNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponsibleEnterpriseNameField, value) != true)) {
                    this.ResponsibleEnterpriseNameField = value;
                    this.RaisePropertyChanged("ResponsibleEnterpriseName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SIF.GWSL.ExampleClient.CaseService.ResponsiblePerson ResponsiblePerson {
            get {
                return this.ResponsiblePersonField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponsiblePersonField, value) != true)) {
                    this.ResponsiblePersonField = value;
                    this.RaisePropertyChanged("ResponsiblePerson");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponsiblePersonName {
            get {
                return this.ResponsiblePersonNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponsiblePersonNameField, value) != true)) {
                    this.ResponsiblePersonNameField = value;
                    this.RaisePropertyChanged("ResponsiblePersonName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponsibleEnterprise", Namespace="http://software-innovation.com/SI.Data")]
    [System.SerializableAttribute()]
    public partial class ResponsibleEnterprise : SIF.GWSL.ExampleClient.CaseService.ContactInfo {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponsiblePerson", Namespace="http://software-innovation.com/SI.Data")]
    [System.SerializableAttribute()]
    public partial class ResponsiblePerson : SIF.GWSL.ExampleClient.CaseService.ContactInfo {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIdField, value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArchiveCodeResult", Namespace="http://software-innovation.com/SI.Data")]
    [System.SerializableAttribute()]
    public partial class ArchiveCodeResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArchiveCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArchiveTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArchiveCode {
            get {
                return this.ArchiveCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ArchiveCodeField, value) != true)) {
                    this.ArchiveCodeField = value;
                    this.RaisePropertyChanged("ArchiveCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArchiveType {
            get {
                return this.ArchiveTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ArchiveTypeField, value) != true)) {
                    this.ArchiveTypeField = value;
                    this.RaisePropertyChanged("ArchiveType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CaseDocumentResult", Namespace="http://software-innovation.com/SI.Data")]
    [System.SerializableAttribute()]
    public partial class CaseDocumentResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SIF.GWSL.ExampleClient.CaseService.CaseDocumentFileResult[] FilesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RecnoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentNumber {
            get {
                return this.DocumentNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentNumberField, value) != true)) {
                    this.DocumentNumberField = value;
                    this.RaisePropertyChanged("DocumentNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SIF.GWSL.ExampleClient.CaseService.CaseDocumentFileResult[] Files {
            get {
                return this.FilesField;
            }
            set {
                if ((object.ReferenceEquals(this.FilesField, value) != true)) {
                    this.FilesField = value;
                    this.RaisePropertyChanged("Files");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Recno {
            get {
                return this.RecnoField;
            }
            set {
                if ((this.RecnoField.Equals(value) != true)) {
                    this.RecnoField = value;
                    this.RaisePropertyChanged("Recno");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CaseCaseRelationResult", Namespace="http://software-innovation.com/SI.Data")]
    [System.SerializableAttribute()]
    public partial class CaseCaseRelationResult : SIF.GWSL.ExampleClient.CaseService.CaseRelation {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CaseDocumentRelationResult", Namespace="http://software-innovation.com/SI.Data")]
    [System.SerializableAttribute()]
    public partial class CaseDocumentRelationResult : SIF.GWSL.ExampleClient.CaseService.DocumentRelation {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CaseDocumentFileResult", Namespace="http://software-innovation.com/SI.Data")]
    [System.SerializableAttribute()]
    public partial class CaseDocumentFileResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FormatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RecnoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Format {
            get {
                return this.FormatField;
            }
            set {
                if ((object.ReferenceEquals(this.FormatField, value) != true)) {
                    this.FormatField = value;
                    this.RaisePropertyChanged("Format");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Recno {
            get {
                return this.RecnoField;
            }
            set {
                if ((this.RecnoField.Equals(value) != true)) {
                    this.RecnoField = value;
                    this.RaisePropertyChanged("Recno");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RelationBase", Namespace="http://software-innovation.com/SI.Data")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SIF.GWSL.ExampleClient.CaseService.DocumentRelation))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SIF.GWSL.ExampleClient.CaseService.CaseDocumentRelationResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SIF.GWSL.ExampleClient.CaseService.CaseRelation))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SIF.GWSL.ExampleClient.CaseService.CaseCaseRelationResult))]
    public partial class RelationBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RelationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Notes {
            get {
                return this.NotesField;
            }
            set {
                if ((object.ReferenceEquals(this.NotesField, value) != true)) {
                    this.NotesField = value;
                    this.RaisePropertyChanged("Notes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Relation {
            get {
                return this.RelationField;
            }
            set {
                if ((object.ReferenceEquals(this.RelationField, value) != true)) {
                    this.RelationField = value;
                    this.RaisePropertyChanged("Relation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentRelation", Namespace="http://software-innovation.com/SI.Data")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SIF.GWSL.ExampleClient.CaseService.CaseDocumentRelationResult))]
    public partial class DocumentRelation : SIF.GWSL.ExampleClient.CaseService.RelationBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentNumber {
            get {
                return this.DocumentNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentNumberField, value) != true)) {
                    this.DocumentNumberField = value;
                    this.RaisePropertyChanged("DocumentNumber");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CaseRelation", Namespace="http://software-innovation.com/SI.Data")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SIF.GWSL.ExampleClient.CaseService.CaseCaseRelationResult))]
    public partial class CaseRelation : SIF.GWSL.ExampleClient.CaseService.RelationBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CaseNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CaseNumber {
            get {
                return this.CaseNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CaseNumberField, value) != true)) {
                    this.CaseNumberField = value;
                    this.RaisePropertyChanged("CaseNumber");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContactInfo", Namespace="http://software-innovation.com/SI.Data")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SIF.GWSL.ExampleClient.CaseService.ResponsiblePerson))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SIF.GWSL.ExampleClient.CaseService.ResponsibleEnterprise))]
    public partial class ContactInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RecnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferencenumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalId {
            get {
                return this.ExternalIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalIdField, value) != true)) {
                    this.ExternalIdField = value;
                    this.RaisePropertyChanged("ExternalId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Recno {
            get {
                return this.RecnoField;
            }
            set {
                if ((this.RecnoField.Equals(value) != true)) {
                    this.RecnoField = value;
                    this.RaisePropertyChanged("Recno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Referencenumber {
            get {
                return this.ReferencenumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferencenumberField, value) != true)) {
                    this.ReferencenumberField = value;
                    this.RaisePropertyChanged("Referencenumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCasesQuery", Namespace="http://software-innovation.com/SI.Data")]
    [System.SerializableAttribute()]
    public partial class GetCasesQuery : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ADContextUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SIF.GWSL.ExampleClient.CaseService.AdditionalFieldParameter[] AdditionalFieldsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArchiveCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CaseNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactReferenceNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SIF.GWSL.ExampleClient.CaseService.ExternalIdParameter ExternalIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IncludeReferringCasesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IncludeReferringDocumentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MaxReturnedCasesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProjectNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ADContextUser {
            get {
                return this.ADContextUserField;
            }
            set {
                if ((object.ReferenceEquals(this.ADContextUserField, value) != true)) {
                    this.ADContextUserField = value;
                    this.RaisePropertyChanged("ADContextUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SIF.GWSL.ExampleClient.CaseService.AdditionalFieldParameter[] AdditionalFields {
            get {
                return this.AdditionalFieldsField;
            }
            set {
                if ((object.ReferenceEquals(this.AdditionalFieldsField, value) != true)) {
                    this.AdditionalFieldsField = value;
                    this.RaisePropertyChanged("AdditionalFields");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArchiveCode {
            get {
                return this.ArchiveCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ArchiveCodeField, value) != true)) {
                    this.ArchiveCodeField = value;
                    this.RaisePropertyChanged("ArchiveCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CaseNumber {
            get {
                return this.CaseNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CaseNumberField, value) != true)) {
                    this.CaseNumberField = value;
                    this.RaisePropertyChanged("CaseNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryCode {
            get {
                return this.CategoryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryCodeField, value) != true)) {
                    this.CategoryCodeField = value;
                    this.RaisePropertyChanged("CategoryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactReferenceNumber {
            get {
                return this.ContactReferenceNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactReferenceNumberField, value) != true)) {
                    this.ContactReferenceNumberField = value;
                    this.RaisePropertyChanged("ContactReferenceNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SIF.GWSL.ExampleClient.CaseService.ExternalIdParameter ExternalId {
            get {
                return this.ExternalIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalIdField, value) != true)) {
                    this.ExternalIdField = value;
                    this.RaisePropertyChanged("ExternalId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IncludeReferringCases {
            get {
                return this.IncludeReferringCasesField;
            }
            set {
                if ((this.IncludeReferringCasesField.Equals(value) != true)) {
                    this.IncludeReferringCasesField = value;
                    this.RaisePropertyChanged("IncludeReferringCases");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IncludeReferringDocuments {
            get {
                return this.IncludeReferringDocumentsField;
            }
            set {
                if ((this.IncludeReferringDocumentsField.Equals(value) != true)) {
                    this.IncludeReferringDocumentsField = value;
                    this.RaisePropertyChanged("IncludeReferringDocuments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MaxReturnedCases {
            get {
                return this.MaxReturnedCasesField;
            }
            set {
                if ((this.MaxReturnedCasesField.Equals(value) != true)) {
                    this.MaxReturnedCasesField = value;
                    this.RaisePropertyChanged("MaxReturnedCases");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProjectNumber {
            get {
                return this.ProjectNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectNumberField, value) != true)) {
                    this.ProjectNumberField = value;
                    this.RaisePropertyChanged("ProjectNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://software-innovation.com/SI.Data", ConfigurationName="CaseService.ICaseService")]
    public interface ICaseService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://software-innovation.com/SI.Data/ICaseService/Ping", ReplyAction="http://software-innovation.com/SI.Data/ICaseService/PingResponse")]
        void Ping();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://software-innovation.com/SI.Data/ICaseService/CreateCase", ReplyAction="http://software-innovation.com/SI.Data/ICaseService/CreateCaseResponse")]
        SIF.GWSL.ExampleClient.CaseService.CaseOperationResult CreateCase(SIF.GWSL.ExampleClient.CaseService.CreateCaseParameter parameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://software-innovation.com/SI.Data/ICaseService/GetCases", ReplyAction="http://software-innovation.com/SI.Data/ICaseService/GetCasesResponse")]
        SIF.GWSL.ExampleClient.CaseService.GetCasesResult GetCases(SIF.GWSL.ExampleClient.CaseService.GetCasesQuery parameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://software-innovation.com/SI.Data/ICaseService/UpdateCase", ReplyAction="http://software-innovation.com/SI.Data/ICaseService/UpdateCaseResponse")]
        SIF.GWSL.ExampleClient.CaseService.CaseOperationResult UpdateCase(SIF.GWSL.ExampleClient.CaseService.UpdateCaseParameter parameter);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICaseServiceChannel : SIF.GWSL.ExampleClient.CaseService.ICaseService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CaseServiceClient : System.ServiceModel.ClientBase<SIF.GWSL.ExampleClient.CaseService.ICaseService>, SIF.GWSL.ExampleClient.CaseService.ICaseService {
        
        public CaseServiceClient() {
        }
        
        public CaseServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CaseServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CaseServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CaseServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Ping() {
            base.Channel.Ping();
        }
        
        public SIF.GWSL.ExampleClient.CaseService.CaseOperationResult CreateCase(SIF.GWSL.ExampleClient.CaseService.CreateCaseParameter parameter) {
            return base.Channel.CreateCase(parameter);
        }
        
        public SIF.GWSL.ExampleClient.CaseService.GetCasesResult GetCases(SIF.GWSL.ExampleClient.CaseService.GetCasesQuery parameter) {
            return base.Channel.GetCases(parameter);
        }
        
        public SIF.GWSL.ExampleClient.CaseService.CaseOperationResult UpdateCase(SIF.GWSL.ExampleClient.CaseService.UpdateCaseParameter parameter) {
            return base.Channel.UpdateCase(parameter);
        }
    }
}
