//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIF.GWSL.ExampleClient.ContactService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetContactPersonsParameter", Namespace="http://software-innovation.com/SI.Data")]
    [System.SerializableAttribute()]
    public partial class GetContactPersonsParameter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ADContextUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] CategoriesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> RecnoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ADContextUser {
            get {
                return this.ADContextUserField;
            }
            set {
                if ((object.ReferenceEquals(this.ADContextUserField, value) != true)) {
                    this.ADContextUserField = value;
                    this.RaisePropertyChanged("ADContextUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Categories {
            get {
                return this.CategoriesField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriesField, value) != true)) {
                    this.CategoriesField = value;
                    this.RaisePropertyChanged("Categories");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalId {
            get {
                return this.ExternalIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalIdField, value) != true)) {
                    this.ExternalIdField = value;
                    this.RaisePropertyChanged("ExternalId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Recno {
            get {
                return this.RecnoField;
            }
            set {
                if ((this.RecnoField.Equals(value) != true)) {
                    this.RecnoField = value;
                    this.RaisePropertyChanged("Recno");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WSOperationResult", Namespace="http://software-innovation.com/SI.Data")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SIF.GWSL.ExampleClient.ContactService.GetPrivatePersonsResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SIF.GWSL.ExampleClient.ContactService.GetEnterprisesResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SIF.GWSL.ExampleClient.ContactService.SynchronizePrivatePersonResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SIF.GWSL.ExampleClient.ContactService.SynchronizeEnterpriseResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SIF.GWSL.ExampleClient.ContactService.SynchronizeContactPersonResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SIF.GWSL.ExampleClient.ContactService.GetContactPersonsResult))]
    public partial class WSOperationResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessfulField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDetails {
            get {
                return this.ErrorDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorDetailsField, value) != true)) {
                    this.ErrorDetailsField = value;
                    this.RaisePropertyChanged("ErrorDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Successful {
            get {
                return this.SuccessfulField;
            }
            set {
                if ((this.SuccessfulField.Equals(value) != true)) {
                    this.SuccessfulField = value;
                    this.RaisePropertyChanged("Successful");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPrivatePersonsResult", Namespace="http://software-innovation.com/SI.Data")]
    [System.SerializableAttribute()]
    public partial class GetPrivatePersonsResult : SIF.GWSL.ExampleClient.ContactService.WSOperationResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SIF.GWSL.ExampleClient.ContactService.PrivatePersonBase[] PrivatePersonsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SIF.GWSL.ExampleClient.ContactService.PrivatePersonBase[] PrivatePersons {
            get {
                return this.PrivatePersonsField;
            }
            set {
                if ((object.ReferenceEquals(this.PrivatePersonsField, value) != true)) {
                    this.PrivatePersonsField = value;
                    this.RaisePropertyChanged("PrivatePersons");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetEnterprisesResult", Namespace="http://software-innovation.com/SI.Data")]
    [System.SerializableAttribute()]
    public partial class GetEnterprisesResult : SIF.GWSL.ExampleClient.ContactService.WSOperationResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SIF.GWSL.ExampleClient.ContactService.EnterpriseResult[] EnterprisesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SIF.GWSL.ExampleClient.ContactService.EnterpriseResult[] Enterprises {
            get {
                return this.EnterprisesField;
            }
            set {
                if ((object.ReferenceEquals(this.EnterprisesField, value) != true)) {
                    this.EnterprisesField = value;
                    this.RaisePropertyChanged("Enterprises");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SynchronizePrivatePersonResult", Namespace="http://software-innovation.com/SI.Data")]
    [System.SerializableAttribute()]
    public partial class SynchronizePrivatePersonResult : SIF.GWSL.ExampleClient.ContactService.WSOperationResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RecnoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Recno {
            get {
                return this.RecnoField;
            }
            set {
                if ((this.RecnoField.Equals(value) != true)) {
                    this.RecnoField = value;
                    this.RaisePropertyChanged("Recno");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SynchronizeEnterpriseResult", Namespace="http://software-innovation.com/SI.Data")]
    [System.SerializableAttribute()]
    public partial class SynchronizeEnterpriseResult : SIF.GWSL.ExampleClient.ContactService.WSOperationResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RecnoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Recno {
            get {
                return this.RecnoField;
            }
            set {
                if ((this.RecnoField.Equals(value) != true)) {
                    this.RecnoField = value;
                    this.RaisePropertyChanged("Recno");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SynchronizeContactPersonResult", Namespace="http://software-innovation.com/SI.Data")]
    [System.SerializableAttribute()]
    public partial class SynchronizeContactPersonResult : SIF.GWSL.ExampleClient.ContactService.WSOperationResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RecnoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Recno {
            get {
                return this.RecnoField;
            }
            set {
                if ((this.RecnoField.Equals(value) != true)) {
                    this.RecnoField = value;
                    this.RaisePropertyChanged("Recno");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetContactPersonsResult", Namespace="http://software-innovation.com/SI.Data")]
    [System.SerializableAttribute()]
    public partial class GetContactPersonsResult : SIF.GWSL.ExampleClient.ContactService.WSOperationResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SIF.GWSL.ExampleClient.ContactService.ContactPersonBase[] ContactPersonsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SIF.GWSL.ExampleClient.ContactService.ContactPersonBase[] ContactPersons {
            get {
                return this.ContactPersonsField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactPersonsField, value) != true)) {
                    this.ContactPersonsField = value;
                    this.RaisePropertyChanged("ContactPersons");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContactPersonBase", Namespace="http://software-innovation.com/SI.Data")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SIF.GWSL.ExampleClient.ContactService.SynchronizeContactPersonParameter))]
    public partial class ContactPersonBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] CategoriesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomNo1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomNo2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomNo3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnterpriseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<SIF.GWSL.ExampleClient.ContactService.Gender> GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobilePhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SIF.GWSL.ExampleClient.ContactService.Address PostAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SIF.GWSL.ExampleClient.ContactService.Address PrivateAddressField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Categories {
            get {
                return this.CategoriesField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriesField, value) != true)) {
                    this.CategoriesField = value;
                    this.RaisePropertyChanged("Categories");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomNo1 {
            get {
                return this.CustomNo1Field;
            }
            set {
                if ((object.ReferenceEquals(this.CustomNo1Field, value) != true)) {
                    this.CustomNo1Field = value;
                    this.RaisePropertyChanged("CustomNo1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomNo2 {
            get {
                return this.CustomNo2Field;
            }
            set {
                if ((object.ReferenceEquals(this.CustomNo2Field, value) != true)) {
                    this.CustomNo2Field = value;
                    this.RaisePropertyChanged("CustomNo2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomNo3 {
            get {
                return this.CustomNo3Field;
            }
            set {
                if ((object.ReferenceEquals(this.CustomNo3Field, value) != true)) {
                    this.CustomNo3Field = value;
                    this.RaisePropertyChanged("CustomNo3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Enterprise {
            get {
                return this.EnterpriseField;
            }
            set {
                if ((object.ReferenceEquals(this.EnterpriseField, value) != true)) {
                    this.EnterpriseField = value;
                    this.RaisePropertyChanged("Enterprise");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalId {
            get {
                return this.ExternalIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalIdField, value) != true)) {
                    this.ExternalIdField = value;
                    this.RaisePropertyChanged("ExternalId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<SIF.GWSL.ExampleClient.ContactService.Gender> Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((this.GenderField.Equals(value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiddleName {
            get {
                return this.MiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MiddleNameField, value) != true)) {
                    this.MiddleNameField = value;
                    this.RaisePropertyChanged("MiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobilePhone {
            get {
                return this.MobilePhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.MobilePhoneField, value) != true)) {
                    this.MobilePhoneField = value;
                    this.RaisePropertyChanged("MobilePhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SIF.GWSL.ExampleClient.ContactService.Address PostAddress {
            get {
                return this.PostAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.PostAddressField, value) != true)) {
                    this.PostAddressField = value;
                    this.RaisePropertyChanged("PostAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SIF.GWSL.ExampleClient.ContactService.Address PrivateAddress {
            get {
                return this.PrivateAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.PrivateAddressField, value) != true)) {
                    this.PrivateAddressField = value;
                    this.RaisePropertyChanged("PrivateAddress");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PrivatePersonBase", Namespace="http://software-innovation.com/SI.Data")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SIF.GWSL.ExampleClient.ContactService.SynchronizePrivatePersonParameter))]
    public partial class PrivatePersonBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] CategoriesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomNo1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomNo2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomNo3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<SIF.GWSL.ExampleClient.ContactService.Gender> GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobilePhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PersonalIdNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SIF.GWSL.ExampleClient.ContactService.Address PostAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SIF.GWSL.ExampleClient.ContactService.Address PrivateAddressField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Categories {
            get {
                return this.CategoriesField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriesField, value) != true)) {
                    this.CategoriesField = value;
                    this.RaisePropertyChanged("Categories");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomNo1 {
            get {
                return this.CustomNo1Field;
            }
            set {
                if ((object.ReferenceEquals(this.CustomNo1Field, value) != true)) {
                    this.CustomNo1Field = value;
                    this.RaisePropertyChanged("CustomNo1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomNo2 {
            get {
                return this.CustomNo2Field;
            }
            set {
                if ((object.ReferenceEquals(this.CustomNo2Field, value) != true)) {
                    this.CustomNo2Field = value;
                    this.RaisePropertyChanged("CustomNo2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomNo3 {
            get {
                return this.CustomNo3Field;
            }
            set {
                if ((object.ReferenceEquals(this.CustomNo3Field, value) != true)) {
                    this.CustomNo3Field = value;
                    this.RaisePropertyChanged("CustomNo3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalID {
            get {
                return this.ExternalIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalIDField, value) != true)) {
                    this.ExternalIDField = value;
                    this.RaisePropertyChanged("ExternalID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<SIF.GWSL.ExampleClient.ContactService.Gender> Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((this.GenderField.Equals(value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiddleName {
            get {
                return this.MiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MiddleNameField, value) != true)) {
                    this.MiddleNameField = value;
                    this.RaisePropertyChanged("MiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobilePhone {
            get {
                return this.MobilePhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.MobilePhoneField, value) != true)) {
                    this.MobilePhoneField = value;
                    this.RaisePropertyChanged("MobilePhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonalIdNumber {
            get {
                return this.PersonalIdNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonalIdNumberField, value) != true)) {
                    this.PersonalIdNumberField = value;
                    this.RaisePropertyChanged("PersonalIdNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SIF.GWSL.ExampleClient.ContactService.Address PostAddress {
            get {
                return this.PostAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.PostAddressField, value) != true)) {
                    this.PostAddressField = value;
                    this.RaisePropertyChanged("PostAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SIF.GWSL.ExampleClient.ContactService.Address PrivateAddress {
            get {
                return this.PrivateAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.PrivateAddressField, value) != true)) {
                    this.PrivateAddressField = value;
                    this.RaisePropertyChanged("PrivateAddress");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://software-innovation.com/SI.Data")]
    [System.SerializableAttribute()]
    public partial class Address : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipPlaceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Area {
            get {
                return this.AreaField;
            }
            set {
                if ((object.ReferenceEquals(this.AreaField, value) != true)) {
                    this.AreaField = value;
                    this.RaisePropertyChanged("Area");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string County {
            get {
                return this.CountyField;
            }
            set {
                if ((object.ReferenceEquals(this.CountyField, value) != true)) {
                    this.CountyField = value;
                    this.RaisePropertyChanged("County");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StreetAddress {
            get {
                return this.StreetAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetAddressField, value) != true)) {
                    this.StreetAddressField = value;
                    this.RaisePropertyChanged("StreetAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode {
            get {
                return this.ZipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipCodeField, value) != true)) {
                    this.ZipCodeField = value;
                    this.RaisePropertyChanged("ZipCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipPlace {
            get {
                return this.ZipPlaceField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipPlaceField, value) != true)) {
                    this.ZipPlaceField = value;
                    this.RaisePropertyChanged("ZipPlace");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SynchronizePrivatePersonParameter", Namespace="http://software-innovation.com/SI.Data")]
    [System.SerializableAttribute()]
    public partial class SynchronizePrivatePersonParameter : SIF.GWSL.ExampleClient.ContactService.PrivatePersonBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ADContextUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataSourceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ADContextUser {
            get {
                return this.ADContextUserField;
            }
            set {
                if ((object.ReferenceEquals(this.ADContextUserField, value) != true)) {
                    this.ADContextUserField = value;
                    this.RaisePropertyChanged("ADContextUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataSource {
            get {
                return this.DataSourceField;
            }
            set {
                if ((object.ReferenceEquals(this.DataSourceField, value) != true)) {
                    this.DataSourceField = value;
                    this.RaisePropertyChanged("DataSource");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Gender", Namespace="http://software-innovation.com/SI.Data")]
    public enum Gender : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Female = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Male = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnterpriseResult", Namespace="http://software-innovation.com/SI.Data")]
    [System.SerializableAttribute()]
    public partial class EnterpriseResult : SIF.GWSL.ExampleClient.ContactService.EnterpriseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SIF.GWSL.ExampleClient.ContactService.EnterpriseContactResult[] ContactRelationsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SIF.GWSL.ExampleClient.ContactService.EnterpriseContactResult[] ContactRelations {
            get {
                return this.ContactRelationsField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactRelationsField, value) != true)) {
                    this.ContactRelationsField = value;
                    this.RaisePropertyChanged("ContactRelations");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnterpriseBase", Namespace="http://software-innovation.com/SI.Data")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SIF.GWSL.ExampleClient.ContactService.SynchronizeEnterpriseParameter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SIF.GWSL.ExampleClient.ContactService.EnterpriseResult))]
    public partial class EnterpriseBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] CategoriesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomNo1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomNo2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomNo3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnterpriseNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InitialsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobilePhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SIF.GWSL.ExampleClient.ContactService.Address OfficeAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParentEnterpriseNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SIF.GWSL.ExampleClient.ContactService.Address PostAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WebField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Categories {
            get {
                return this.CategoriesField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriesField, value) != true)) {
                    this.CategoriesField = value;
                    this.RaisePropertyChanged("Categories");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomNo1 {
            get {
                return this.CustomNo1Field;
            }
            set {
                if ((object.ReferenceEquals(this.CustomNo1Field, value) != true)) {
                    this.CustomNo1Field = value;
                    this.RaisePropertyChanged("CustomNo1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomNo2 {
            get {
                return this.CustomNo2Field;
            }
            set {
                if ((object.ReferenceEquals(this.CustomNo2Field, value) != true)) {
                    this.CustomNo2Field = value;
                    this.RaisePropertyChanged("CustomNo2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomNo3 {
            get {
                return this.CustomNo3Field;
            }
            set {
                if ((object.ReferenceEquals(this.CustomNo3Field, value) != true)) {
                    this.CustomNo3Field = value;
                    this.RaisePropertyChanged("CustomNo3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnterpriseNumber {
            get {
                return this.EnterpriseNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.EnterpriseNumberField, value) != true)) {
                    this.EnterpriseNumberField = value;
                    this.RaisePropertyChanged("EnterpriseNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalID {
            get {
                return this.ExternalIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalIDField, value) != true)) {
                    this.ExternalIDField = value;
                    this.RaisePropertyChanged("ExternalID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Initials {
            get {
                return this.InitialsField;
            }
            set {
                if ((object.ReferenceEquals(this.InitialsField, value) != true)) {
                    this.InitialsField = value;
                    this.RaisePropertyChanged("Initials");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobilePhone {
            get {
                return this.MobilePhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.MobilePhoneField, value) != true)) {
                    this.MobilePhoneField = value;
                    this.RaisePropertyChanged("MobilePhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SIF.GWSL.ExampleClient.ContactService.Address OfficeAddress {
            get {
                return this.OfficeAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.OfficeAddressField, value) != true)) {
                    this.OfficeAddressField = value;
                    this.RaisePropertyChanged("OfficeAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParentEnterpriseNumber {
            get {
                return this.ParentEnterpriseNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentEnterpriseNumberField, value) != true)) {
                    this.ParentEnterpriseNumberField = value;
                    this.RaisePropertyChanged("ParentEnterpriseNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SIF.GWSL.ExampleClient.ContactService.Address PostAddress {
            get {
                return this.PostAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.PostAddressField, value) != true)) {
                    this.PostAddressField = value;
                    this.RaisePropertyChanged("PostAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefax {
            get {
                return this.TelefaxField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefaxField, value) != true)) {
                    this.TelefaxField = value;
                    this.RaisePropertyChanged("Telefax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Web {
            get {
                return this.WebField;
            }
            set {
                if ((object.ReferenceEquals(this.WebField, value) != true)) {
                    this.WebField = value;
                    this.RaisePropertyChanged("Web");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SynchronizeEnterpriseParameter", Namespace="http://software-innovation.com/SI.Data")]
    [System.SerializableAttribute()]
    public partial class SynchronizeEnterpriseParameter : SIF.GWSL.ExampleClient.ContactService.EnterpriseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ADContextUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SIF.GWSL.ExampleClient.ContactService.ContactContactParameter[] ContactRelationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataSourceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ADContextUser {
            get {
                return this.ADContextUserField;
            }
            set {
                if ((object.ReferenceEquals(this.ADContextUserField, value) != true)) {
                    this.ADContextUserField = value;
                    this.RaisePropertyChanged("ADContextUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SIF.GWSL.ExampleClient.ContactService.ContactContactParameter[] ContactRelations {
            get {
                return this.ContactRelationsField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactRelationsField, value) != true)) {
                    this.ContactRelationsField = value;
                    this.RaisePropertyChanged("ContactRelations");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataSource {
            get {
                return this.DataSourceField;
            }
            set {
                if ((object.ReferenceEquals(this.DataSourceField, value) != true)) {
                    this.DataSourceField = value;
                    this.RaisePropertyChanged("DataSource");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnterpriseContactResult", Namespace="http://software-innovation.com/SI.Data")]
    [System.SerializableAttribute()]
    public partial class EnterpriseContactResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContactContactParameter", Namespace="http://software-innovation.com/SI.Data")]
    [System.SerializableAttribute()]
    public partial class ContactContactParameter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenceNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalId {
            get {
                return this.ExternalIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalIdField, value) != true)) {
                    this.ExternalIdField = value;
                    this.RaisePropertyChanged("ExternalId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferenceNumber {
            get {
                return this.ReferenceNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceNumberField, value) != true)) {
                    this.ReferenceNumberField = value;
                    this.RaisePropertyChanged("ReferenceNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SynchronizeContactPersonParameter", Namespace="http://software-innovation.com/SI.Data")]
    [System.SerializableAttribute()]
    public partial class SynchronizeContactPersonParameter : SIF.GWSL.ExampleClient.ContactService.ContactPersonBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ADContextUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataSourceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ADContextUser {
            get {
                return this.ADContextUserField;
            }
            set {
                if ((object.ReferenceEquals(this.ADContextUserField, value) != true)) {
                    this.ADContextUserField = value;
                    this.RaisePropertyChanged("ADContextUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataSource {
            get {
                return this.DataSourceField;
            }
            set {
                if ((object.ReferenceEquals(this.DataSourceField, value) != true)) {
                    this.DataSourceField = value;
                    this.RaisePropertyChanged("DataSource");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPrivatePersonsParameter", Namespace="http://software-innovation.com/SI.Data")]
    [System.SerializableAttribute()]
    public partial class GetPrivatePersonsParameter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ADContextUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PersonalIdNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> RecnoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ADContextUser {
            get {
                return this.ADContextUserField;
            }
            set {
                if ((object.ReferenceEquals(this.ADContextUserField, value) != true)) {
                    this.ADContextUserField = value;
                    this.RaisePropertyChanged("ADContextUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalID {
            get {
                return this.ExternalIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalIDField, value) != true)) {
                    this.ExternalIDField = value;
                    this.RaisePropertyChanged("ExternalID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonalIdNumber {
            get {
                return this.PersonalIdNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonalIdNumberField, value) != true)) {
                    this.PersonalIdNumberField = value;
                    this.RaisePropertyChanged("PersonalIdNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Recno {
            get {
                return this.RecnoField;
            }
            set {
                if ((this.RecnoField.Equals(value) != true)) {
                    this.RecnoField = value;
                    this.RaisePropertyChanged("Recno");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetEnterprisesParameter", Namespace="http://software-innovation.com/SI.Data")]
    [System.SerializableAttribute()]
    public partial class GetEnterprisesParameter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ADContextUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] CategoriesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnterpriseNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> RecnoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ADContextUser {
            get {
                return this.ADContextUserField;
            }
            set {
                if ((object.ReferenceEquals(this.ADContextUserField, value) != true)) {
                    this.ADContextUserField = value;
                    this.RaisePropertyChanged("ADContextUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Categories {
            get {
                return this.CategoriesField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriesField, value) != true)) {
                    this.CategoriesField = value;
                    this.RaisePropertyChanged("Categories");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnterpriseNumber {
            get {
                return this.EnterpriseNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.EnterpriseNumberField, value) != true)) {
                    this.EnterpriseNumberField = value;
                    this.RaisePropertyChanged("EnterpriseNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalID {
            get {
                return this.ExternalIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalIDField, value) != true)) {
                    this.ExternalIDField = value;
                    this.RaisePropertyChanged("ExternalID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Recno {
            get {
                return this.RecnoField;
            }
            set {
                if ((this.RecnoField.Equals(value) != true)) {
                    this.RecnoField = value;
                    this.RaisePropertyChanged("Recno");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://software-innovation.com/SI.Data", ConfigurationName="ContactService.IContactService")]
    public interface IContactService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://software-innovation.com/SI.Data/IContactService/Ping", ReplyAction="http://software-innovation.com/SI.Data/IContactService/PingResponse")]
        void Ping();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://software-innovation.com/SI.Data/IContactService/GetContactPersons", ReplyAction="http://software-innovation.com/SI.Data/IContactService/GetContactPersonsResponse")]
        SIF.GWSL.ExampleClient.ContactService.GetContactPersonsResult GetContactPersons(SIF.GWSL.ExampleClient.ContactService.GetContactPersonsParameter parameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://software-innovation.com/SI.Data/IContactService/GetPrivatePersons", ReplyAction="http://software-innovation.com/SI.Data/IContactService/GetPrivatePersonsResponse")]
        SIF.GWSL.ExampleClient.ContactService.GetPrivatePersonsResult GetPrivatePersons(SIF.GWSL.ExampleClient.ContactService.GetPrivatePersonsParameter parameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://software-innovation.com/SI.Data/IContactService/GetEnterprises", ReplyAction="http://software-innovation.com/SI.Data/IContactService/GetEnterprisesResponse")]
        SIF.GWSL.ExampleClient.ContactService.GetEnterprisesResult GetEnterprises(SIF.GWSL.ExampleClient.ContactService.GetEnterprisesParameter parameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://software-innovation.com/SI.Data/IContactService/SynchronizePrivatePerson", ReplyAction="http://software-innovation.com/SI.Data/IContactService/SynchronizePrivatePersonRe" +
            "sponse")]
        SIF.GWSL.ExampleClient.ContactService.SynchronizePrivatePersonResult SynchronizePrivatePerson(SIF.GWSL.ExampleClient.ContactService.SynchronizePrivatePersonParameter parameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://software-innovation.com/SI.Data/IContactService/SynchronizeEnterprise", ReplyAction="http://software-innovation.com/SI.Data/IContactService/SynchronizeEnterpriseRespo" +
            "nse")]
        SIF.GWSL.ExampleClient.ContactService.SynchronizeEnterpriseResult SynchronizeEnterprise(SIF.GWSL.ExampleClient.ContactService.SynchronizeEnterpriseParameter parameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://software-innovation.com/SI.Data/IContactService/SynchronizeContactPerson", ReplyAction="http://software-innovation.com/SI.Data/IContactService/SynchronizeContactPersonRe" +
            "sponse")]
        SIF.GWSL.ExampleClient.ContactService.SynchronizeContactPersonResult SynchronizeContactPerson(SIF.GWSL.ExampleClient.ContactService.SynchronizeContactPersonParameter parameter);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IContactServiceChannel : SIF.GWSL.ExampleClient.ContactService.IContactService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ContactServiceClient : System.ServiceModel.ClientBase<SIF.GWSL.ExampleClient.ContactService.IContactService>, SIF.GWSL.ExampleClient.ContactService.IContactService {
        
        public ContactServiceClient() {
        }
        
        public ContactServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ContactServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContactServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContactServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Ping() {
            base.Channel.Ping();
        }
        
        public SIF.GWSL.ExampleClient.ContactService.GetContactPersonsResult GetContactPersons(SIF.GWSL.ExampleClient.ContactService.GetContactPersonsParameter parameter) {
            return base.Channel.GetContactPersons(parameter);
        }
        
        public SIF.GWSL.ExampleClient.ContactService.GetPrivatePersonsResult GetPrivatePersons(SIF.GWSL.ExampleClient.ContactService.GetPrivatePersonsParameter parameter) {
            return base.Channel.GetPrivatePersons(parameter);
        }
        
        public SIF.GWSL.ExampleClient.ContactService.GetEnterprisesResult GetEnterprises(SIF.GWSL.ExampleClient.ContactService.GetEnterprisesParameter parameter) {
            return base.Channel.GetEnterprises(parameter);
        }
        
        public SIF.GWSL.ExampleClient.ContactService.SynchronizePrivatePersonResult SynchronizePrivatePerson(SIF.GWSL.ExampleClient.ContactService.SynchronizePrivatePersonParameter parameter) {
            return base.Channel.SynchronizePrivatePerson(parameter);
        }
        
        public SIF.GWSL.ExampleClient.ContactService.SynchronizeEnterpriseResult SynchronizeEnterprise(SIF.GWSL.ExampleClient.ContactService.SynchronizeEnterpriseParameter parameter) {
            return base.Channel.SynchronizeEnterprise(parameter);
        }
        
        public SIF.GWSL.ExampleClient.ContactService.SynchronizeContactPersonResult SynchronizeContactPerson(SIF.GWSL.ExampleClient.ContactService.SynchronizeContactPersonParameter parameter) {
            return base.Channel.SynchronizeContactPerson(parameter);
        }
    }
}
